project:
  type: website

website:
  title: "Robyn" 
  navbar:
    title: false
    left:
      - href: index.qmd
        text: HOME
      - text: "ABOUT"
        menu:
          - text: "ABOUT ME"
            href: about.qmd
          - text: "MY WORK"
            href: work.qmd
      - text: "RECIPES"
        href: recipes.qmd
      - text: "RESTAURANTS"
        href: restaurants.qmd
      - text: "TIE DYES"
        href: tiedyes.qmd
      - icon: github
        href: https://github.com/rmarow
      - icon: twitter
        href: https://twitter.com/rmarowitz

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



